### ISSUE TITLE
Как подвинуть фрейм влево.

### ISSUE THREAD

**Issue by stemplock** [Alkohole/udr#1]
Спасибо за скрипт. Очень выручили. 
Как бы это бредово не звучало, приходится использовать его для Yandex Browser на Linux.
Вопрос в заголовке. Как подвинуть фрейм влево и можно ли его сделать плавающим?

**Comment by Alkohole** [comment]
На данный момент, вы можете самостоятельно, в скрипте расширения, отредактировать все `.style.right` на `.style.left` чтобы отправить окно в левый край экрана, если вы хотите только сдвинуть его от края, то вам придется суммировать к этим параметрам число в пикселях, на которое вы хотите передвинуть окно и кнопки.
Расширения браузера - Tampermonkey - [MRT] - Править. (Нужные вам строчки: 41, 61, 73, 78, 86, 107)


В будущем, я добавлю позиционирование в настройки, и сами настройки.
По поводу "плавающего окна", я как раз думал об этом, возможно в следующем обновлении.

**Comment by Alkohole** [comment]
@stemplock 
Я добавил настройки в которых есть возможность сместить окно по горизонтали.
Так же добавил возможность установить сторону позиционирования.
Для того чтобы задать параметры по умолчанию вам нужно отредактировать только 2 переменных в скрипте:
https://github.com/Alkohole/machine-reading-text/blob/fe8f3278a5f6529f2cc64e8d6cf6b191560cf40c/mrt.user.js#L25-L26
Или воспользоватся настройками для сдвига (имеет временное действие)
